### PR TITLE
Clean up compile warnings

### PR DESCRIPTION
**Pull request by JoshuaSBrown**
OpenMP and Events not being initialized warnings addressed.

### CODE REVIEW

**Comment by JoshuaSBrown** [comment]
Note if we merge this with master first we can then pull it into the development branch.

**Comment by MikeHeiber** [comment]
I would also like almost all updates merged into development.  I'd like merges into master to only be done for releases.

**Comment by JoshuaSBrown** [comment]
Ok, how about having them pass in a flag when they call make if they want to run with openMP?

**Comment by MikeHeiber** [comment]
That could work nicely.  Would you still be able to suppress the compiler warning for when users do not include the openmp flag?

**Comment by JoshuaSBrown** [comment]
Yes :)

**Comment by MikeHeiber** [comment]
This change then also proposes to add a new feature, which is openmp support/capabilities.  Currently, I only have openmp pramga's in one place, mainly for personal testing.  After thinking about it a bit more, instead of implementing openmp here, I suggest adding it as a feature request and just commenting out the pragma statements that are currently there.

**Comment by JoshuaSBrown** [comment]
I think something is broken on here I just pushed two commits but they are not showing up here. Though if you go to insights->network you can see them.

**Comment by JoshuaSBrown** [comment]
@MikeHeiber Your Bkl algorithm has broken the development branch by the way.

**Comment by JoshuaSBrown** [comment]
Ok fixed the problem. We can do that if you want but no one is going to be using the openmp option anyway unless we tell them to use the flag this way it is already implemented. I can still of course just comment it out.

**Comment by MikeHeiber** [comment]
Will users now need to have openmp installed in order to build and use Excimontec?  I'd prefer to avoid unnecessary dependencies unless they offer real, tested feature benefits.

**Comment by JoshuaSBrown** [comment]
If I put a guard around the include <omp.h> they won't need to.

**Comment by MikeHeiber** [comment]
I have decided that I do not want to support openmp in the code unless it has a clear beneficial use for the users.  Right now it's not really going to be doing anything, so I'd rather just leave it out for simplicity.  If we decide that it will be very helpful to have it later, we can add it then.

**Pull request merged**
